# Ansible Inventory for TaskFlow EC2 Deployment

[ec2_instances]
taskflow-server ansible_host=13.218.98.235 ansible_user=ubuntu ansible_ssh_private_key_file=~/taskflow-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ec2_instances:vars]
docker_hub_repo=hansadisr/taskflow
image_tag=latest


